---
name: ((deployment_name))                         # 서비스 배포이름(필수) 

releases:
- name: ((service_release_name))             # 서비스 릴리즈 이름(필수)
  version: ((service_release_version))       # 서비스 릴리즈 버전(필수):latest 시 업로드된 서비스 릴리즈 최신버전

stemcells:
- alias: default
  os: ((stemcell_os))
  version: ((stemcell_version))

update:
  canaries: 1                            # canary 인스턴스 수(필수)
  canary_watch_time: 30000-600000        # canary 인스턴스가 수행하기 위한 대기 시간milliseconds (필수)
  max_in_flight: 1                       # non-canary 인스턴스가 병렬로 update 하는 최대 개수(필수)
  update_watch_time: 10000-600000         # non-canary 인스턴스가 수행하기 위한 대기 시간milliseconds (필수)
  serial: true

instance_groups:
- name: mariadb
  azs: ((mariadb_azs))
  instances: ((mariadb_instances))
  persistent_disk_type: ((mariadb_persistent_disk_type))
  vm_type: ((vm_type_default))
  stemcell: default
  networks:
  - name: ((private_networks_name))
  jobs:
  - name: mariadb
    release: ((service_release_name))
    properties:
      port: ((mariadb_port))
      admin:
        password: ((mariadb_admin_password))
      service:
        username: ((mariadb_service_username))
        password: ((mariadb_service_password))
  update:
    max_in_flight: 1

- name: service-broker
  azs: ((broker_azs))
  instances: ((broker_instances))
  vm_type: ((vm_type_default))
  stemcell: default
  networks:
  - name: ((private_networks_name))
  jobs:
  - name: service-broker
    release: ((service_release_name))
    properties:
      port: ((broker_port))
      logging:
        level_broker: ((broker_logging_level_broker))
        level_hibernate: ((broker_logging_level_hibernate))
      dashboard:
        url: ((broker_dashboard_url))
      services:
        id: ((broker_services_id))
        plans:
          id: ((broker_services_plans_id))
  update:
    max_in_flight: 1

