# RELEASE
service_release_name: "PAAS-TA-APP-LIFECYCLE-SERVICE-RELEASE"
service_release_version: "1.0"
deployment_name: "paasta-lifecycle-service"

# STEMCELL
stemcell_os: "ubuntu-xenial"
stemcell_version: "315.45"

# VM_TYPE
vm_type_minimal: "minimal"
vm_type_default: "small"
vm_type_medium: "medium"

# NETWORK
private_networks_name: "service_private"
public_networks_name: "service_public"
public_networks_ips: "[public_ips]" # [111.11.11.111,222.22.22.222,333.33.33.333]

# TAIGA
taiga_azs: [z5]
taiga_user: taiga
taiga_port: 80
taiga_admin_password: "<TAIGA_ADMIN_PASSWORD>"
postgresql_password: "<POSTGRES_PASSWORD>"
postgresql_db_name: taiga

# MARIA_DB
mariadb_azs: [z5]
mariadb_instances: 1
mariadb_persistent_disk_type: "10GB"
mariadb_port: "<MARIADB_PORT>"
mariadb_admin_password: "<MARIADB_ADMIN_PASSWORD>"
mariadb_service_username: "<MARIADB_SERVICE_USERNAME>"
mariadb_service_password: "<MARIADB_SERVICE_PASSWORD>"

# SERVICE-BROKER
broker_azs: [z5]
broker_instances: 1
broker_port: "<SERVICE_BROKER_PORT>"
broker_logging_level_broker: "INFO"
broker_logging_level_hibernate: "INFO"
broker_dashboard_url: "<SERVICE_BROKER_DASHBOARD_URL>" # Not Support. 현재 public_ip를 url로 사용하고있
broker_services_id: "<SERVICE_BROKER_SERVICES_GUID>"
broker_services_plans_id: "<SERVICE_BROKER_SERVICES_PLANS_GUID>"
taiga_service_instance_name: "taiga"
